name: powerloader
channels:
- conda-forge
dependencies:
  - cmake
  - ninja
  - cxx-compiler
  - libcurl
  - openssl
  - nlohmann_json
  - cli11
  # Not available on Windows
  - sel(unix): zchunk
  - spdlog
  - gtest
  # necessary for gtest cmake to work properly
  - gmock
  - yaml-cpp
  - pytest
  - pyyaml
  - gh
  - pip:
    - pytest-xprocess
    - versionfinder
