name: powerloader-dev
channels:
  - conda-forge
dependencies:
  # libpowerloader-static
  - cmake
  - ninja
  - cxx-compiler
  - libcurl-static >=7.88.1
  - openssl
  - libopenssl-static
  - libnghttp2-static
  - zstd-static
  - libssh2-static
  - krb5-static
  - zchunk-static
  - cpp-expected
  - spdlog
  - nlohmann_json
  # powerloader
  - cli11
  - yaml-cpp
  # Tests
  - doctest
