name: powerloader-dev
channels:
  - conda-forge
dependencies:
  - vs2019_win-64
  - ninja
  - cpp-expected
  - spdlog
  - nlohmann_json
  - zchunk-static
  - libcurl-static
  - zstd-static
  - libopenssl-static
  # Tests
  - doctest
